# this file can't be named differently
name: 'Docker Action Recipe'
description: 'This workflow demonstrates how to consume input and run a docker container.'

inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  answer:
    description: 'The answer to everything (always 42)'
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: '/bin/sh'
  args: 
    - '-c'
    - 'echo "Hello ${{ inputs.who-to-greet }}!" && echo "answer=42" >> $GITHUB_OUTPUT'