# A first worklfow to play around with the editor
name: My First Workflow
on: # triggers when the workflow should run
  push:
    branches:
      - main
      - 'release/**'
    paths:
      - 'doc/**'
  schedule:
    #- cron: '*/15 * * * *'
    #- cron: '0 9-17 * * *'
    - cron: '0 2 * * FRI'
  workflow_dispatch: # enable manual trigger by UI; you can use input here!

jobs:
  first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - name: Greet the user
        run: | # starts a multiline block
          echo "Hello world from ${{ github.actor }}"
          echo "Current branch is ${{ github.ref }}"
        shell: bash # optional. bash is default for non-windows platforms
      - name: Checkout
        uses: actions/checkout@v4.2.2 #using github actions
      - name: display files after checking out
        run: tree
        
